### ISSUE TITLE
Question: geo calculations

### ISSUE THREAD

**Issue by petercoppensdatylon** [zellige/hs-geojson#30]
Hello

At first sight hs-geojson does not have functionality to do geo calculations (mainly looking for containment of points in polygones), region overlap, ...)

Anyone has tips on how to go about that? Perhaps some other Haskell library can be combined to get there?

Tx!!

Peter

**Comment by newmana** [comment]
Last time I looked, there were no pure Haskell libraries that did this. It was a longer term goal we had (we did WKT and WKB parsing in Haskell for example). We ended up using PostGIS a lot too.

The main library people use is geos https://github.com/ewestern/geos which is a binding to the C library.
